package KieRule;
import  org.nasr.app.Order;

rule "Medical"

when
orderObject : Order(productType=="medical" );
then
orderObject.setDiscount(0.10);
orderObject.setTax(0);
orderObject.totalPrice();
end;


rule "groceries"

when
orderObject : Order(productType=="groceries");
then
orderObject.setDiscount(0.5);
orderObject.setTax(0.14);
orderObject.totalPrice();
end;


rule "luxury goods"

when
orderObject : Order(productType=="luxury goods");
then
orderObject.setDiscount(0);
orderObject.setTax(0.14);
orderObject.totalPrice();
end;

rule "mobile"

when
orderObject : Order( name=="mobile");
then
orderObject.setDiscount(0);
orderObject.setTax(0.14);
orderObject.totalPrice();
end;
